### ISSUE TITLE
blurry in high dpi scaling

### ISSUE THREAD

**Issue by thekingofcity** [HMBSbige/TCPingInfoView#1]
![20181017203254](https://user-images.githubusercontent.com/3353040/47086473-254dc000-d24c-11e8-924b-a576d970216a.jpg)

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/TCPingInfoView/commit/8593ebc70422153e2f17edf11cc53d6c3fb24818#diff-f20af10dbcec4544224bad09c1f9d7b2

**Comment by HMBSbige** [comment]
At least Windows 10 Build 15063 (Creators Update) for this fix
